name = "tutor-api"
main = "src/index.js"
compatibility_date = "2026-08-01"

routes = [
  { pattern = "works.lrnr.jp/api/*", zone_name = "lrnr.jp" },
]

[vars]
FIREBASE_PROJECT_ID = "grocery-checker-14fd9"
ALLOWED_EMAIL = "ryoxsakai@gmail.com"
ALLOWED_ORIGIN = "https://works.lrnr.jp"

[[d1_databases]]
binding = "DB"
database_name = "tutor-db"
database_id = "941460fb-c46e-4158-b4a7-5bb468b542ca"
